# Generated by Django 4.2.7 on 2023-11-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('ingredient', models.CharField(max_length=100)),
                ('recipe', models.CharField(max_length=5000)),
                ('image', models.CharField(max_length=3000)),
            ],
        ),
    ]
