# Generated by Django 4.2.7 on 2023-11-28 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='recipe',
            new_name='recipebook',
        ),
    ]
